### ISSUE TITLE
Strongpassword throws a warning about URI.open being deprecated

### ISSUE THREAD

**Issue by morganestes** [vitorgalvao/homebrew-tiny-scripts#3]
On macOS 10.14.6, when I run `strongpassword` in the terminal, it gives two warnings before telling me that the password's been copied to the clipboard. It doesn't seem to affect the functionality in the few times I've run it.

```
❯ strongpassword
/usr/local/bin/strongpassword:21: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/usr/local/bin/strongpassword:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
Password copied to clipboard (64 characters)
```

I've looked at the source of `strongpassword.rb` and honestly can't figure out how the executable script gets generated so I'm not even sure how to create a patch for it, but I found a patch in Rails that looks like it could work: https://github.com/rails/rails/commit/d16f39ded273a3c019e78bca52e8e196e5214cc9. I'm happy to try and patch and test if you can tell me where to find the script source.

**Comment by vitorgalvao** [comment]
Fixed. I’ve also renamed it, so you should `brew uninstall strongpassword && brew install strong-password`.
