### ISSUE TITLE
HEAD is now at a0ae3a9 Fix download file path is not retrieved correctly (#199)

### ISSUE THREAD

**Issue by mbierman** [vitorgalvao/homebrew-tiny-scripts#4]
I'm sorry if this is a dumb question but what does this error mean and how do I fix it? 

```
bigmac:Casks michael$ brew uninstall cask-repair
Error: No installed keg or cask with the name "cask-repair"
bigmac:Casks michael$ brew install cask-repair
Updating Homebrew...
==> Installing cask-repair from vitorgalvao/tiny-scripts
==> Cloning https://github.com/vitorgalvao/tiny-scripts.git
Updating /Users/bierman/Library/Caches/Homebrew/cask-repair--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at a0ae3a9 Fix download file path is not retrieved correctly (#199)
🍺  /usr/local/Cellar/cask-repair/0.40.26: 5 files, 26.3KB, built in 16 seconds
```

**Comment by vitorgalvao** [comment]
That’s not an error, it’s just information.

It means that the [HEAD](https://stackoverflow.com/questions/2304087/what-is-head-in-git) of [the cloned repository](https://github.com/vitorgalvao/tiny-scripts) is at the commit [Fix download file path is not retrieved correctly (#199)](https://github.com/vitorgalvao/tiny-scripts/commit/a0ae3a97a51aac72d1bba2ca7c4dea5512e64560), which is [the latest one](https://github.com/vitorgalvao/tiny-scripts/commits/master).
